language: python

python:
    - "2.6"
    - "2.7"
    - "3.4"
    - "3.5"

install:
    - python setup.py install
    - pip install readme_renderer

script:
    - nosetests
    - python setup.py check -r -s

after_success:
  - bash <(curl -s https://codecov.io/bash)
